### PR TITLE
Bug Fix for issue regarding Reverse

### LINKED ISSUE #3: Reverse does not work
... because the copy/move constructor is not called while the other ctor

    template <typename Eter>
    constexpr reverse_enumerator(Eter&& eter)

is called twice

### PR DESCRIPTION
**Pull request by theSundayProgrammer**
This is a suggested fix for the issue I raised 

Fixes #3

### CODE REVIEW

**Comment by Berrysoft** [comment]
@theSundayProgrammer Many thanks for your bug report and pull request! But it seems that your change doesn't pass my original test.
Test report:
```
Expected: <6> as i
Actual: <1> as i
File: ../test/test_utility.hpp
Line: 16
Func: void bstest::test_equals(E1&&, E2&&, const char*, const char*, std::size_t) [with E1 = int (&)[6]; E2 = linq::enumerable<linq::impl::reverse_enumerator<int> >&; std::size_t = long unsigned int]
At:
File: ../test/aggregate_test.cpp
Line: 44
Func: void aggregate_test::reverse_test()
```
I noticed that it is because the code here:
https://github.com/Berrysoft/CppLinq/blob/5f019a90d2f2682f8e9e85dfcf89dd251559f498/test/test_utility.hpp#L13
It calls the template constructor instead of the copy constructor. Could you help me fix it?

**Comment by theSundayProgrammer** [comment]
I am using catch2 test framework. All the tests in `aggregate` pass. Check my fork.

Sorry for the late reply. I forgot to change my email address in Github.

**Comment by theSundayProgrammer** [comment]
OMG! I didn't read you message properly. I am working on it now

**Comment by theSundayProgrammer** [comment]
The following patch appears to fix the issue. I must confess, I have not understood why `std::option` 
calls the main ctor if it is not explicit rather than the copy ctor

    diff --git a/include/linq/aggregate.hpp b/include/linq/aggregate.hpp
    index 9df1f54..ea86c18 100644
    --- a/include/linq/aggregate.hpp
    +++ b/include/linq/aggregate.hpp
    @@ -406,6 +406,7 @@ namespace linq
             }
 
                 template <typename Eter>
    +            explicit
                constexpr reverse_enumerator(Eter&& eter)
               {
                 for (; eter; ++eter)

**Comment by Berrysoft** [comment]
Thanks very much!

**Pull request merged**
